const helpers = require('yeoman-test');
const path = require('path');
const fs = require('fs-extra');
const assert = require('yeoman-assert');

describe('Check file for yo', () => {
  const prompts = { 'appName': 'ITArverne generated by test', 'template': 'origin' };
  const options = { 'skip-install': true };

  it('verify the right template', function () {
    return helpers.run(path.join(__dirname, '../app'))
      .withPrompts({ template: 'origin' })
      .inTmpDir(function (dir) {
        const done = this.async();
        fs.copySync(path.join(__dirname, '../app/templates', prompts['template']), dir, done)
      })
      .then(function (dir) {
        assert.file(path.join(__dirname, '../app/templates', prompts['template'], '/index.html'));
      });
  });

  it('verify the app', function () {
    app = helpers.createGenerator(
      'itarverne-landing-page:app', [path.join(__dirname, '../app')], false, options
    );
    helpers.mockPrompt(app, prompts);
    app.run(function () {
      // assert something
      done();
    });
  });

});