const helpers = require('yeoman-test');
const path = require('path');
const assert = require('yeoman-assert');
const sinon = require('sinon');

describe('Check console for yo', () => {
  const prompts = { 
    'appName': 'ITArverne generated by test-console'
  };
  const options = { 'skip-install': true };

  it('verify no error appear from console', function () {
    sinon.spy(console, "error");

    helpers.run(path.join(__dirname, '../app'))
    assert(console.error.notCalled);
  });

});