language: node_js

node_js:
  - "8"

branches:
  except:
  - experimental

cache:
  directories:
  - "node_modules"

before_script:
  - npm install grunt-cli -g
  - gem install sass
  - npm install -g yo

script:
  - grunt build