language: node_js

node_js:
  - "8"

branches:
  except:
  - experimental

cache:
  directories:
  - "node_modules"

before_script:
  - npm install -g grunt-cli
  - gem install sass
  - npm install -g yo
  - npm link

script:
  - cd public && grunt build