language: node_js

env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPORTER_ID
    - GH_COMPANY=$GH_COMPANY
    - GH_USER=$GH_USER
    - GH_EMAIL=$GH_EMAIL
    - NAME_REPO=$NAME_REPO
    - GH_REPO="github.com/${GH_COMPANY}/${NAME_REPO}.git"
    - ADD_FILES="public/*"

node_js:
  - "8"

branches:
  except:
  - experimental

cache:
  directories:
  - "node_modules"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install -g grunt-cli
  - gem install sass
  - npm install -g yo
  - npm link

script:
  - npm test


after_success:
  - git clone git://${GH_REPO}
  - yes | cp -rf ${ADD_FILES} ${NAME_REPO}/
  - cd ${NAME_REPO}
  - git remote
  - git config user.email ${GH_EMAIL}
  - git config user.name ${GH_USER}
  - git pull
  - git add ${ADD_FILES}
  - git commit -m "Push auto from generator-itarverne-landing-page github repo"
  - git push "https://${GH_USER}:${GH_PWD}@${GH_REPO}"
  # Get last message commit, extract name tag
  - TAG_TO_CREATE = git log -1 --pretty=%B | grep -oP "CREATE TAG v?\K([0-9.]*)"
  - if [ ${TAG_TO_CREATE} ]; then
      BEFORE_LAST_COMMIT_TAG = git log --skip=1 --grep="CREATE TAG" --pretty=%H
      NEW_CHANGELOG = git log ${BEFORE_LAST_COMMIT_TAG}.. --no-merges --pretty=format:'- %s'
      sed -i '1s/^/##[$BEFORE_LAST_COMMIT_TAG]/' CHANGELOG.md
      sed -i '1s/^/$NEW_CHANGELOG/' CHANGELOG.md
      git add CHANGELOG.md
      git commit -m "Auto generate CHANGELOG"
      git push "https://${GH_USER}:${GH_PWD}@${GH_REPO}"
    fi

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT





