language: node_js

env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPORTER_ID
    - GH_COMPANY=$GH_COMPANY
    - GH_USER=$GH_USER
    - GH_EMAIL=$GH_EMAIL
    - NAME_REPO=$NAME_REPO
    - GH_REPO="github.com/${GH_COMPANY}/${NAME_REPO}.git"
    - ADD_FILES="public/"

node_js:
  - "8"

branches:
  except:
  - experimental

cache:
  directories:
  - "node_modules"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install -g grunt-cli
  - gem install sass
  - npm install -g yo
  - npm link

script:
  - npm test

after_success:
  - git clone git://${GH_REPO}
  - mv -f ${ADD_FILES} ${NAME_REPO}
  - cd ${NAME_REPO}
  - git remote
  - git config user.email ${GH_EMAIL}
  - git config user.name ${GH_USER}
  - git add ${ADD_FILES}
  - git commit -m "Push auto from generator-itarverne-landing-page github repo"
  - git push "https://${GH_REPO}" master > /dev/null 2>&1
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
